---
title: "tpcbass_drc_fitting"
author: "ross"
date: "2/13/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(drc)
library(quantreg)
library(mcr)
library(broom)
library(lubridate)
library(tidyverse)

# Create custom ggplot theme
theme_custom <- function() {
  theme_bw(base_size = 10, base_family = "Arial") %+replace%
    theme(
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), 
      panel.background = element_blank(),
      panel.border = element_rect(color = "black", fill = NA),
      legend.background = element_rect(fill = NA, colour = NA),
      axis.title = element_text(size = 7),
      axis.text = element_text(size = 5)
    )
}

# Function to pivot IPAM data to long form with column for AOI
ipam_convert <- function(data) {
  data %>% select_if(~ !any(is.na(.))) %>%
  pivot_longer(cols = starts_with("f") | starts_with("y")) %>%
  separate(name, into = c("var", "aoi"), sep = "(?<=[A-Za-z_])(?=[0-9])")
}
```

# Import rack, temperature, and coral position information
```{r}
# Import coral collection data
corals <- readxl::read_xlsx("data/collection_metadata.xlsx") %>%
  janitor::clean_names()

# Import coral identification data (morphology and mtORF)
id <- read_csv("data/morphology.csv") %>%
  janitor::clean_names()

# Import CBASS metadata (positions of corals on racks, and CBASS temperatures of each rack)
rack_pos <- read_csv("data/CBASS/CBASS_rack_position_map.csv")
rack_temp <- read_csv("data/CBASS/CBASS_rack_temp_map.csv")

# Re-number positions by order on racks with empty positions
rack_pos <- rack_pos %>%
  group_by(rack_config) %>%
  filter(basket_no != "X") %>%          # used to indicate empty position on rack
  mutate(position = row_number()) %>%   # renumber pos. in same order, but w/o empty pos.
  mutate(basket_no = as.numeric(basket_no))

# Join CBASS metadata
md <- full_join(rack_temp, rack_pos)
md <- md %>%
  unite(rack, rack_no, rack_config, sep = "") %>%
  mutate(date = as_date(as.character(date)))
```

# Import I-PAM data
```{r}
# Import PAM data
# List PAM files
pamfiles <- list.files(path = "data/CBASS", pattern = "(^\\d).*.csv", 
                       recursive = TRUE, full.names = TRUE)

# Import data from each file
pam1 <- pamfiles %>%
  map_dfr(read_delim, delim = ";", .id = "file_id") %>%
  janitor::clean_names() %>%
  mutate(file_id = basename(pamfiles[as.numeric(file_id)]),
         date = as_date(date, format = "%d.%m.%y"))

# # For files that have multiple sat pulses -- keep the last one only
pam1 <- pam1 %>%
  group_by(file_id, date) %>%
  filter(no == max(no)) %>%
  ungroup()

# For each source file, convert to long form data with F, FM, and YII for each AOI
pam1 <- pam1 %>%
  nest(-file_id, -date) %>%
  mutate(data2 = map(data, ipam_convert)) %>%
  unnest(data2) %>%
  group_by(file_id, date) %>%
  select(file_id, date, time, aoi, var, value)

pam1 <- pam1 %>%
  separate(file_id, into = c("rack", "junk"))
  

# Join PAM data with rack order information (which PAM file corresponds to which rack of corals)
pam <- pam1 %>%
  group_by(rack, date) %>%
  mutate(position = ceiling(as.numeric(aoi)/2)) %>%
  ungroup()

pam <- left_join(pam, md) %>% left_join(corals, by = "basket_no")
```

# Fit dose-response curves
```{r}
# Get Fv/Fm data and tidy
df <- pam %>%
  mutate(max_temp = as.numeric(temp)) %>%
  pivot_wider(names_from = var, values_from = value) %>%
  mutate(fvfmraw = y_ii_, fvfm = y_ii_) %>%
  select(date, tag_number, max_temp, f, fm, fvfmraw, fvfm)
# Average technical replicates
df <- df %>%
  group_by(date, tag_number, max_temp) %>%
  summarize(fvfmraw = mean(fvfmraw),
            fvfm = mean(fvfm)) %>%
  ungroup()

# Define function to fit 3-parameter LL model to data and return NULL if fitting error
ll3 <- function(data) {
  drm(fvfm ~ max_temp, data = data, 
      fct = LL.3(names = c("hill", "max", "ED50")))}#,
      # upperl = c(50, 0.7, 40),
      # lowerl = c(20, 0.3, 30))}
tryll3 <- possibly(ll3, otherwise = NULL)

# Fit model to each coral, get parameters, fitted values, and residuals
initmods <- df %>%
  nest(data = c(date, max_temp, fvfmraw, fvfm)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
ed50 <- initmods %>% 
  select(tag_number, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# Extract all drc parameters
allpars <- initmods %>%
  select(tag_number, pars) %>%
  unnest(pars)

write_csv(allpars, path = "data/processed/CBASS_allpars_ind.csv")

hist(ed50$estimate, breaks = 30)

# Collect raw data, fitted values, and diagnostics
vals <- initmods %>%
  select(tag_number, pred) %>%
  unnest(pred) %>%
  full_join(ed50) %>%
  full_join(df) %>%
  rename(ed50 = estimate) %>%
  mutate(problem = "none")
```

# Plot dose response curves for each genotype
```{r plot, fig.width = 10, fig.height = 10}
ed50 <- ed50 %>%
  mutate(geno = factor(tag_number))

vals <- vals %>%
  mutate(geno = fct_reorder(factor(tag_number), ed50, .fun = mean))

ggplot(vals, aes(x = max_temp, y = fvfm)) +
  geom_point() +
  geom_line(aes(y = .fitted)) +
  geom_vline(aes(xintercept = estimate), data = ed50, lty = 2) +
  geom_text(aes(x = estimate, y = 0.05, label = round(estimate, 2)), data = ed50,
            size = 2, nudge_x = -1.5) +
  facet_wrap(~geno)
```

# Data filtering/QC from dose-response curves
```{r drc_diagnostics}
# # Identify problematic data points based on cook's distance and residuals
counts <- vals %>%
  mutate(geno = tag_number) %>%
  group_by(geno) %>%
  summarise(n = sum(!is.na(fvfm)))
dff <- vals %>%
  mutate(geno = tag_number) %>%
  left_join(counts) %>%
  group_by(geno) %>%
  mutate(cooksd.thresh = 4/n) %>%   # Calculate cook's distance threshold as 4/n
  mutate(max_to_remove = floor(n * 0.2)) %>%
  ungroup() %>%
  mutate(problem = case_when(.cooksd > cooksd.thresh ~ "high cook's distance",
                             TRUE ~ "none")) %>%
  group_by(geno, outlier = problem %in% c("high cook's distance", "high residual")) %>%
  mutate(n.outliers = n(),
         rank.out = order(.cooksd, decreasing = TRUE)) %>%
  ungroup() %>%
  mutate(fvfm = case_when(outlier & rank.out <= max_to_remove ~ .fitted,
                          TRUE ~ fvfm))

# Refit models without problematic points
fmods <- dff %>%
  select(geno, max_temp, fvfmraw, problem, fvfm) %>%
  nest(data = c(max_temp, fvfmraw, fvfm, problem)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
fed50 <- fmods %>%
  select(geno, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# Extract all drc parameters
allfpars <- fmods %>%
  select(tag_number = geno, pars) %>%
  unnest(pars)

write_csv(allfpars, path = "data/processed/CBASS_allfpars_ind.csv")

# Collect raw data, fitted values, and ed50 estimates
fvals <- fmods %>%
  select(geno, pred) %>%
  unnest(pred) %>%
  full_join(fed50) %>%
  full_join(select(dff, geno, max_temp, fvfmraw, problem, fvfm)) %>%
  rename(ed50 = estimate)


fed50 <- fed50 %>%
  mutate(geno = factor(geno))

fvals <- fvals %>%
  mutate(geno = factor(geno)) %>%
  mutate(geno = fct_reorder(geno, ed50, .fun = mean))

# Plot filtered drcs
ggplot(fvals, aes(x = max_temp, y = fvfm)) +
  geom_point() +
  geom_line(aes(y = .fitted)) +
  geom_vline(aes(xintercept = estimate), data = fed50, lty = 2) +
  geom_text(aes(x = estimate, y = 0.05, label = round(estimate, 2)), data = fed50,
            size = 2, nudge_x = -1.5) +
  facet_wrap(~geno)

```


```{r}
# Join individual genotype DRC parameters with species ID
fvals2 <- fvals %>% left_join(mutate(id, geno = factor(number)))
fed502 <- fed50 %>% left_join(mutate(id, geno = factor(number)))# %>%
  #filter(tpcbass == "Yes")

# Which corals CBASSed have no haplotype info?
fed50 %>% left_join(mutate(id, geno = factor(number))) %>% 
  select(geno, estimate, species) %>% 
  print(n = nrow(.))

# Plot ED50 values by haplotype group
ggplot(fed502 ,aes(x = species, y = estimate, color = species)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  labs(x = "mtORF", y = "ED50 (°C)") +
  theme(legend.position = "none")

# ANOVA on filtered ED50s between haplotype groups
mod <- lm(estimate ~ species, data = filter(fed502, !is.na(species)))
anova(mod)
emmeans::emmeans(mod, specs = "species")
bartlett.test(estimate ~ species, data = filter(fed502, !is.na(species)))

# Significant difference-- Haplotype 1a have higher mean ED50 than Haplotype 3b colonies
# Mean of Hap1a ED50 = 36.1, Mean Hap3b ED50 = 35.8
# Not sig when only 6 corals of each species (the number that were TPCd)
```


### Fit DRCs for species groups instead of individuals
```{r}
# Prefiltering for outliers for each spp/temp
df <- df %>%
  left_join(mutate(id, tag_number = number)) %>%
  mutate(group = paste0(species, "_", max_temp))
#set quantile values
q <- c(0.25, 0.75)

# calculate quantile values by Temperature and Treatment groups
Quants <- df %>%
  group_by(species, max_temp) %>%
  summarize(quant25 = quantile(fvfm, probs = q[1]),
            quant75 = quantile(fvfm, probs = q[2]),
            IQRbyGroup=IQR(fvfm))

# add a group name by pasting Temperature and Treatment
Quants$group <-paste0(Quants$species,"_", Quants$max_temp)

#Calculate Quantile upper and lower ranges
Quants$upper <-  Quants$quant75+1.5*Quants$IQRbyGroup # Upper Range
Quants$lower <- Quants$quant25-1.5*Quants$IQRbyGroup # Lower Range

#join outlier cutoffs with rate data
df <- left_join(df, Quants, by="group")

#remove outliers from rates
x <- df %>%
  filter(fvfm <= upper) %>%
  filter(fvfm >= lower) #%>%
  #filter(rate < 0.125)



# Fit model to each group, get parameters, fitted values, and residuals
df2 <- x %>% #left_join(mutate(id, tag_number = number)) %>%
  filter(tpcbass == "Yes") %>%
  select(species = species.x,  tag_number, date, max_temp = max_temp.x,  fvfmraw, fvfm) %>%
  mutate(species2 = case_when(species == "P. grandis" ~ "Pgra",
                              species == "P. verrucosa" ~ "Pver"))

modn <- drm(fvfm ~ max_temp, data = df2,
    fct = LL.3(names = c("hill", "max", "ED50")))
mod <- drm(fvfm ~ max_temp, curveid = species2, data = df2,
    fct = LL.3(names = c("hill", "max", "ED50")))
augment(mod, df2) %>%
  arrange(-.cooksd)
anova(mod, modn, test = "Chisq")
AIC(mod, modn)
mod


# Significant difference between mt_orf groups when DRC fitted to each group
# Haplotype 1a ED50 = 35.86, Haplotype 3b ED50 = 35.53 (with data filterd post-individal DRCs)
# Haplotype 1a ED50 = 35.85, Haplotype 3b ED50 = 35.57 (with unfiltered/all datapoints)

#plot(mod)
plot(mod, type = "all", xlim = c(33, 38))

# Bootstrap confidence intervals
coef(mod)
confints <- car::Boot(mod, R = 500, method = "case") %>%
  confint(., method = 'bca', level = 0.9) %>%
  as.data.frame() %>%
  rename(conf_lower = 1, conf_upper = 2) %>%
  rownames_to_column(., var = 'param') %>%
  mutate(method = 'case bootstrap')

# write results with conf to file...
tidy(mod) %>%
  #filter(term == "ED50") %>%
  mutate(species = case_when(curve == "Pver" ~ "P. verrucosa",
                           curve == "Pgra" ~ "P. grandis")) %>%
  select(species, term, estimate, std.error) %>%
  bind_cols(confints) %>%
  select(species, term, estimate, conf_lower, conf_upper) %>%
  write_csv("data/processed/CBASS_allpars_grp.csv")
```


# Write results to file
```{r, eval = F}
# fed50 %>%
#   mutate(fragment_ID = paste("POC", geno, sep = "-")) %>%
#   select(fragment_ID, estimate, std.error) %>%
#   write_csv("data/processed/CBASS_ED50s_ind.csv")
# 
# tidy(mod) %>%
#   #filter(term == "ED50") %>%
#   mutate(species = case_when(curve == "Pver" ~ "P. verrucosa",
#                            curve == "Pgra" ~ "P. grandis")) %>%
#   select(species, term, estimate, std.error) %>%
#   write_csv("data/processed/CBASS_allpars_grp.csv")

  
```

