---
title: "compare_cbass_tpc"
author: "ross"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Import data

```{r}
library(tidyverse)
library(ggpubr)
library(broom)


# Import CBASS parameters - individual and group fits
cbass_ind <- read_csv("data/processed/CBASS_allfpars_ind.csv") %>%
  mutate(fragment_ID = paste("POC", tag_number, sep = "-"))
cbass_grp <- read_csv("data/processed/CBASS_allpars_grp.csv")

# Import TPC parameters - group fits
tpc_dec_rezende_grp <- read.csv("data/processed/TPC_Dec_Photo_params_rezende_grp.csv")
tpc_may_rezende_grp <- read.csv("data/processed/TPC_May_Photo_params_rezende_grp.csv")
tpc_grp <- bind_rows(.id = "tpc",
                     dec22 = tpc_dec_rezende_grp,
                     may22 = tpc_may_rezende_grp) %>%
  pivot_longer(cols = 3:13, names_to = "param")

# Import TPC parameters - individual fits
tpc_dec_rezende_ind <- read.csv("data/processed/TPC_Dec_Photo_params_rezende_ind.csv")
tpc_may_rezende_ind <- read.csv("data/processed/TPC_May_Photo_params_rezende_ind.csv")
# Combine individual fits
tpc_ind <- bind_rows(.id = "tpc",
                     dec22 = tpc_dec_rezende_ind, 
                     may22 = tpc_may_rezende_ind) %>%
  select(tpc, species, fragment_ID, rss, rmax, topt, ctmax, e, eh, q10, thermal_safety_margin, thermal_tolerance, breadth) %>%
  pivot_longer(cols = 4:12, names_to = "param")


# Join CBASS and TPC group parameters
grp <- inner_join(cbass_grp, tpc_grp)

# Join CBASS and TPC individual parameters
ind <- inner_join(cbass_ind, tpc_ind)

```


# Compare TPC parameters with CBASS parameters

### P. grandis vs. P. verrucosa (group fits)
```{r, fig.width = 4, fig.height = 12}
grp %>% 
  filter(term == "ED50") %>%
  filter(param %in% c("topt", "ctmax", "eh", "breadth", "rmax")) %>%
  ggplot(aes(x = estimate, y = value)) +
  geom_point(aes(shape = species)) +
  geom_errorbar(aes(xmin = estimate - std.error, xmax = estimate + std.error), width = 0) +
  facet_grid(param~tpc, scales = "free") +
  theme(legend.position = "bottom") +
  labs(title = "ED50")

grp %>% 
  filter(term == "hill") %>%
  filter(param %in% c("topt", "ctmax", "eh", "breadth", "rmax")) %>%
  ggplot(aes(x = estimate, y = value)) +
  geom_point(aes(shape = species)) +
  geom_errorbar(aes(xmin = estimate - std.error, xmax = estimate + std.error), width = 0) +
  facet_grid(param~tpc, scales = "free") +
  theme(legend.position = "bottom") +
  labs(title = "hill")

grp %>% 
  filter(term == "max") %>%
  filter(param %in% c("topt", "ctmax", "eh", "breadth", "rmax")) %>%
  ggplot(aes(x = estimate, y = value)) +
  geom_point(aes(shape = species)) +
  geom_errorbar(aes(xmin = estimate - std.error, xmax = estimate + std.error), width = 0) +
  facet_grid(param~tpc, scales = "free") +
  theme(legend.position = "bottom") +
  labs(title = "max")
```

### All individual corals (individual fits)

```{r, fig.width = 4, fig.height = 12}
library(ggpubr)

#ED50
ind %>% filter(term == "ED50") %>%
  ggplot(aes(x = estimate, y = value)) + 
  #geom_errorbar(aes(xmin = ed50 - std.error, xmax = ed50 + std.error)) +
  geom_point(aes(color = species, shape = species)) +
  geom_smooth(method = "lm", se = FALSE,  lwd = 0.5) +
  stat_cor(method = "spearman") +
  facet_grid(param ~ tpc, scales = "free") +
  theme(legend.position = "bottom") +
  labs(title = "ED50")

# Hill
ind %>% filter(term == "hill") %>%
  ggplot(aes(x = estimate, y = value)) + 
  #geom_errorbar(aes(xmin = ed50 - std.error, xmax = ed50 + std.error)) +
  geom_point(aes(color = species, shape = species)) +
  geom_smooth(method = "lm", se = FALSE,  lwd = 0.5) +
  stat_cor(method = "spearman") +
  facet_grid(param ~ tpc, scales = "free") +
  theme(legend.position = "bottom") +
  labs(title = "hill")

# Max
ind %>% filter(term == "max") %>%
  ggplot(aes(x = estimate, y = value)) + 
  #geom_errorbar(aes(xmin = ed50 - std.error, xmax = ed50 + std.error)) +
  geom_point(aes(color = species, shape = species)) +
  geom_smooth(method = "lm", se = FALSE,  lwd = 0.5) +
  stat_cor(method = "spearman") +
  facet_grid(param ~ tpc, scales = "free") +
  theme(legend.position = "bottom") +
  labs(title = "max")
```

# Do individual coral CBASS ED50s differ between species?
```{r, eval = F}
library(emmeans)
ed50_mod <- lm(ed50 ~ species, data = ed50_ind)
anova(ed50_mod)
emmeans(ed50_mod, specs = "species")

# Yes -- P. grandis (35.9) > P. verrucosa (35.5); p = 0.0345
```

# Do individual coral TPC parameters differ between species?
```{r, eval = F}
tpc_mods <- tpc_ind %>%
  filter(!is.na(species), !param %in% c("ctmin", "q10")) %>%
  group_by(tpc, param) %>%
  nest() %>%
  mutate(mod = map(data, ~ lm(value ~ species, data = .)),
         p = map_dbl(mod, ~ tidy(.)$p.value[2]))

tpc_mods %>% 
  arrange(p) %>%
  print(n = nrow(.))

# No -- no significant differences between species for any parameters
# In the fitting process for group TPC parameters, is there a way to test for statistically significant differences between speceis?
```

